// Code generated by cwgo (v0.1.0). DO NOT EDIT.

package user

import (
	"context"
	"cwgo_test/biz/doc/model/user"
	"cwgo_test/biz/doc/model/video"
	"go.mongodb.org/mongo-driver/mongo"
)

type UserRepository interface {
	InsertOne(ctx context.Context, user *user.User) (interface{}, error)
	InsertMany(ctx context.Context, user []*user.User) ([]interface{}, error)
	FindUsernames(ctx context.Context, skip int64, limit int64) ([]*user.User, error)
	FindByUsernameAge(ctx context.Context, name1 string, name2 string, age int32) (*user.User, error)
	UpdateContact(ctx context.Context, contact *user.UserContact, id int64) (bool, error)
	DeleteById(ctx context.Context, yd []user.YDType) (int, error)
	CountByAge(ctx context.Context, age1 int32, age2 int32) (int, error)
	BulkOp(ctx context.Context, userInsert *user.User, userUpdate *user.User, id int64) (*mongo.BulkWriteResult, error)
	TransactionOp(ctx context.Context, client *mongo.Client, videoCollection *mongo.Collection, userInsert *user.User, userUpdate *user.User, id int64, videos []*video.Video) error
}
