// Code generated by cwgo (v0.1.0). DO NOT EDIT.

package video

import (
	"context"
	"cwgo_test/biz/doc/model/video"
)

type VideoRepository interface {
	InsertVideo(ctx context.Context, video *video.Video) (interface{}, error)
}
